feat: parse ruby spec
artipie/cocoa-adapter pull request #2
Opened 2022-10-28 14:30 UTC by olenagerasimova

Part of #1 
Added classes to parse podspec in ruby format.

2022-10-28 14:31 UTC, olenagerasimova commented
@dgarus please, review

2022-10-31 14:14 UTC, dgarus requested changes
@olenagerasimova thanks!
There are minor comments.

2022-10-31 14:14 UTC, dgarus commented on .rultor.yml
> +docker:
Do we use `rultor` now?

2022-10-31 14:14 UTC, dgarus commented on src/main/java/com/artipie/cocoa/metadata/Podspec.java
> +     * Packages course, type and value map. Check the
`course` -> `sourse`?

2022-10-31 14:20 UTC, olenagerasimova commented
@dgarus thanks, corrected, rultor we do not use now

2022-10-31 14:25 UTC, dgarus approved these changes
@olenagerasimova thanks!

2022-11-01 15:21 UTC, merged